# Generated by Django 4.1.5 on 2023-01-21 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneBrandModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'brand',
                'verbose_name_plural': 'brands',
            },
        ),
        migrations.CreateModel(
            name='PhonesCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='PhonesColorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'color',
                'verbose_name_plural': 'colors',
            },
        ),
        migrations.CreateModel(
            name='PhoneTagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.CreateModel(
            name='PhoneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('os', models.CharField(max_length=15)),
                ('os_version', models.CharField(max_length=15)),
                ('Type_of_sim_card', models.CharField(max_length=15)),
                ('Built_in_memory', models.CharField(max_length=30)),
                ('ram', models.CharField(max_length=15)),
                ('Product_weight_with_packaging_kg', models.CharField(max_length=15)),
                ('Product_height_cm', models.CharField(max_length=15)),
                ('Country_of_manufacture', models.CharField(max_length=10)),
                ('Degree_of_dust_and_moisture_protection', models.CharField(max_length=15)),
                ('Depth_cm', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Display_Screen_Type', models.CharField(max_length=10)),
                ('Screen_diagonal', models.CharField(max_length=15)),
                ('Screen_resolution', models.CharField(max_length=15)),
                ('Processor', models.CharField(max_length=15)),
                ('Number_of_processor_cores', models.CharField(max_length=19)),
                ('Processor_clock_speed', models.CharField(max_length=15)),
                ('Number_of_SIM_cards', models.CharField(max_length=15)),
                ('Communication_standard', models.CharField(max_length=15)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phone', to='car.phonebrandmodel')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phone', to='car.phonescategorymodel')),
                ('color', models.ManyToManyField(related_name='phone', to='car.phonescolormodel')),
                ('tag', models.ManyToManyField(related_name='phone', to='car.phonetagmodel')),
            ],
            options={
                'verbose_name': 'phone',
                'verbose_name_plural': 'phones',
            },
        ),
    ]
