# Generated by Django 4.1.5 on 2023-01-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptopmodel',
            name='Country_of_manufacture',
            field=models.CharField(max_length=100),
        ),
    ]
