# Generated by Django 4.1.5 on 2023-01-29 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0002_alter_laptopmodel_country_of_manufacture'),
    ]

    operations = [
        migrations.CreateModel(
            name='TvBrandModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'brand',
                'verbose_name_plural': 'brands',
            },
        ),
        migrations.CreateModel(
            name='TvCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='TvColorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'color',
                'verbose_name_plural': 'colors',
            },
        ),
        migrations.CreateModel(
            name='TvTagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.AlterField(
            model_name='laptopmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='TvModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(null=True, upload_to='TV')),
                ('price', models.CharField(max_length=50, null=True)),
                ('graphics_card', models.CharField(max_length=50, null=True)),
                ('os_version', models.CharField(max_length=50, null=True)),
                ('HD_Resolution', models.CharField(max_length=50, null=True)),
                ('RAM', models.CharField(max_length=50, null=True)),
                ('Overall_dimensions_without_packaging', models.CharField(max_length=50, null=True)),
                ('Country_of_manufacture', models.CharField(max_length=100, null=True)),
                ('Flash_memory', models.CharField(max_length=50, null=True)),
                ('Screen_resolution', models.CharField(max_length=50, null=True)),
                ('processor', models.CharField(max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('Number_of_colors', models.CharField(max_length=50, null=True)),
                ('Screen_format', models.CharField(max_length=50, null=True)),
                ('Viewing_angle', models.CharField(max_length=50, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tv', to='laptop.tvbrandmodel')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tv', to='laptop.tvcategorymodel')),
                ('color', models.ManyToManyField(related_name='tv', to='laptop.tvcolormodel')),
                ('tag', models.ManyToManyField(related_name='tv', to='laptop.tvtagmodel')),
            ],
            options={
                'verbose_name': 'tv',
                'verbose_name_plural': 'tvs',
            },
        ),
    ]
